import type { Scenario, ScenarioKey } from '@/lib/demo-data';

export type ObservabilityGroup =
  | 'Power'
  | 'Thermal'
  | 'Health'
  | 'Fabric'
  | 'Performance'
  | 'Inventory';

export type ObservabilitySignal = {
  name: string;
  group: ObservabilityGroup;
  value: string;
  threshold: string;
  status: 'Normal' | 'Warning' | 'Critical' | 'Info';
  source: string;
  uri: string;
};

export function buildObservabilityCatalog(
  rack: string,
  node: string,
  gpu: string,
  scenarioKey: ScenarioKey,
  scenario: Scenario,
): ObservabilitySignal[] {
  const gpuId = gpu === 'All GPUs' ? 'GPU0-7' : gpu.replace(' ', '');
  const hot = scenarioKey === 'cooling';
  const capped = scenarioKey === 'power';
  const degraded = scenarioKey === 'pcie';
  const latestPower = scenario.metrics.power.at(-1) ?? 40;
  const latestTemp = scenario.metrics.thermal.at(-1) ?? 24;
  const latestTraffic = scenario.metrics.traffic.at(-1) ?? 3.4;
  const latestClock = scenario.metrics.clock.at(-1) ?? 1820;
  const rf = '/redfish/v1';

  return [
    {
      name: 'Rack power draw',
      group: 'Power',
      value: `${latestPower.toFixed(1)} kW`,
      threshold: 'warn > 45 kW',
      status: capped ? 'Warning' : 'Normal',
      source: 'Chassis Power',
      uri: `${rf}/Chassis/${rack}/Power`,
    },
    {
      name: 'Configured power cap',
      group: 'Power',
      value: `${capped ? '35.0' : '48.0'} kW`,
      threshold: 'static limit',
      status: capped ? 'Critical' : 'Info',
      source: 'PowerControl',
      uri: `${rf}/Chassis/${rack}/Power#/PowerControl/0`,
    },
    {
      name: 'Input voltage L1',
      group: 'Power',
      value: '240.4 V',
      threshold: '208–252 V',
      status: 'Normal',
      source: 'PowerSupply',
      uri: `${rf}/Chassis/${rack}/Power#/PowerSupplies/0`,
    },
    {
      name: 'Input current L1',
      group: 'Power',
      value: `${(latestPower / 0.24).toFixed(0)} A`,
      threshold: 'warn > 195 A',
      status: 'Normal',
      source: 'PowerSupply',
      uri: `${rf}/Chassis/${rack}/Power#/PowerSupplies/0`,
    },
    {
      name: 'PSU A output',
      group: 'Power',
      value: `${(latestPower * 0.51).toFixed(1)} kW`,
      threshold: 'balance ±8%',
      status: 'Normal',
      source: 'PowerSupply',
      uri: `${rf}/Chassis/${rack}/Power#/PowerSupplies/0`,
    },
    {
      name: 'PSU B output',
      group: 'Power',
      value: `${(latestPower * 0.49).toFixed(1)} kW`,
      threshold: 'balance ±8%',
      status: 'Normal',
      source: 'PowerSupply',
      uri: `${rf}/Chassis/${rack}/Power#/PowerSupplies/1`,
    },
    {
      name: 'GPU board power',
      group: 'Power',
      value: `${capped ? 438 : 524} W`,
      threshold: 'crit > 700 W',
      status: capped ? 'Warning' : 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'Cold-aisle inlet',
      group: 'Thermal',
      value: `${latestTemp.toFixed(1)} °C`,
      threshold: 'warn > 27 °C',
      status: hot ? 'Critical' : 'Normal',
      source: 'Thermal Temperature',
      uri: `${rf}/Chassis/${rack}/Thermal#/Temperatures/0`,
    },
    {
      name: 'Hot-aisle exhaust',
      group: 'Thermal',
      value: `${(latestTemp + 11.6).toFixed(1)} °C`,
      threshold: 'warn > 45 °C',
      status: hot ? 'Warning' : 'Normal',
      source: 'Thermal Temperature',
      uri: `${rf}/Chassis/${rack}/Thermal#/Temperatures/1`,
    },
    {
      name: 'Rack delta-T',
      group: 'Thermal',
      value: '11.6 °C',
      threshold: '8–16 °C',
      status: 'Normal',
      source: 'Derived metric',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-Thermal`,
    },
    {
      name: 'Fan-zone duty',
      group: 'Thermal',
      value: `${hot ? 96 : 72}%`,
      threshold: 'warn > 90%',
      status: hot ? 'Warning' : 'Normal',
      source: 'Thermal Fan',
      uri: `${rf}/Chassis/${rack}/Thermal#/Fans`,
    },
    {
      name: 'Fan-zone speed',
      group: 'Thermal',
      value: `${hot ? '15,820' : '12,460'} RPM`,
      threshold: 'crit < 6,000',
      status: 'Normal',
      source: 'Thermal Fan',
      uri: `${rf}/Chassis/${rack}/Thermal#/Fans/0`,
    },
    {
      name: 'GPU core temperature',
      group: 'Thermal',
      value: `${hot ? 78 : 61} °C`,
      threshold: 'warn > 80 °C',
      status: hot ? 'Warning' : 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'HBM temperature',
      group: 'Thermal',
      value: `${hot ? 84 : 67} °C`,
      threshold: 'warn > 85 °C',
      status: hot ? 'Warning' : 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'BMC temperature',
      group: 'Thermal',
      value: '44.2 °C',
      threshold: 'warn > 75 °C',
      status: 'Normal',
      source: 'Manager Thermal',
      uri: `${rf}/Managers/${rack}-${node}/EnvironmentMetrics`,
    },
    {
      name: 'Aggregate chassis health',
      group: 'Health',
      value: scenarioKey === 'healthy' ? 'OK' : 'Warning',
      threshold: 'Status.Health',
      status: scenarioKey === 'healthy' ? 'Normal' : 'Warning',
      source: 'Chassis Status',
      uri: `${rf}/Chassis/${rack}#/Status`,
    },
    {
      name: 'System health rollup',
      group: 'Health',
      value: scenarioKey === 'healthy' ? 'OK' : 'Warning',
      threshold: 'Status.HealthRollup',
      status: scenarioKey === 'healthy' ? 'Normal' : 'Warning',
      source: 'ComputerSystem',
      uri: `${rf}/Systems/${rack}-${node}#/Status`,
    },
    {
      name: 'Active Redfish events',
      group: 'Health',
      value: scenarioKey === 'healthy' ? '0' : '2',
      threshold: 'warn > 0',
      status: scenarioKey === 'healthy' ? 'Normal' : 'Warning',
      source: 'EventService',
      uri: `${rf}/EventService`,
    },
    {
      name: 'SEL entries in window',
      group: 'Health',
      value: scenarioKey === 'healthy' ? '0' : '3',
      threshold: 'warn > 0',
      status: scenarioKey === 'healthy' ? 'Normal' : 'Warning',
      source: 'LogService',
      uri: `${rf}/Systems/${rack}-${node}/LogServices/SEL`,
    },
    {
      name: 'Predictive failure',
      group: 'Health',
      value: 'False',
      threshold: 'must be false',
      status: 'Normal',
      source: 'Drive Status',
      uri: `${rf}/Systems/${rack}-${node}/Storage/NVMe/Drives/0`,
    },
    {
      name: 'BMC heartbeat',
      group: 'Health',
      value: 'Reachable',
      threshold: 'miss 3 polls',
      status: 'Normal',
      source: 'Manager Status',
      uri: `${rf}/Managers/${rack}-${node}#/Status`,
    },
    {
      name: 'Collection latency',
      group: 'Health',
      value: '184 ms',
      threshold: 'warn > 2 s',
      status: 'Normal',
      source: 'Collector',
      uri: `${rf}`,
    },
    {
      name: 'ToR ingress',
      group: 'Fabric',
      value: `${latestTraffic.toFixed(2)} Tb/s`,
      threshold: 'warn > 7.2 Tb/s',
      status: degraded ? 'Critical' : 'Normal',
      source: 'NetworkAdapter',
      uri: `${rf}/Chassis/${rack}/NetworkAdapters/ToR-A`,
    },
    {
      name: 'ToR egress',
      group: 'Fabric',
      value: `${(latestTraffic * 0.91).toFixed(2)} Tb/s`,
      threshold: 'warn > 7.2 Tb/s',
      status: degraded ? 'Warning' : 'Normal',
      source: 'NetworkDeviceFunction',
      uri: `${rf}/Chassis/${rack}/NetworkAdapters/ToR-B`,
    },
    {
      name: 'Fabric error rate',
      group: 'Fabric',
      value: degraded ? '42 /min' : '0.2 /min',
      threshold: 'crit > 10 /min',
      status: degraded ? 'Critical' : 'Normal',
      source: 'Port Metrics',
      uri: `${rf}/Chassis/${rack}/NetworkAdapters/ToR-A/Ports/1/Metrics`,
    },
    {
      name: 'PCIe negotiated width',
      group: 'Fabric',
      value: degraded ? 'x4' : 'x16',
      threshold: 'must equal x16',
      status: degraded ? 'Critical' : 'Normal',
      source: 'PCIeDevice',
      uri: `${rf}/Systems/${rack}-${node}/PCIeDevices/${gpuId}`,
    },
    {
      name: 'PCIe link speed',
      group: 'Fabric',
      value: degraded ? '16 GT/s' : '32 GT/s',
      threshold: 'must equal 32 GT/s',
      status: degraded ? 'Warning' : 'Normal',
      source: 'PCIeDevice',
      uri: `${rf}/Systems/${rack}-${node}/PCIeDevices/${gpuId}`,
    },
    {
      name: 'Host-to-GPU traffic',
      group: 'Fabric',
      value: degraded ? '18.4 GB/s' : '58.2 GB/s',
      threshold: 'warn < 36 GB/s',
      status: degraded ? 'Critical' : 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'NVLink throughput',
      group: 'Fabric',
      value: '312 GB/s',
      threshold: 'warn < 240 GB/s',
      status: 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'Correctable PCIe errors',
      group: 'Fabric',
      value: degraded ? '428' : '2',
      threshold: 'warn > 100 /h',
      status: degraded ? 'Warning' : 'Normal',
      source: 'PCIeDevice Metrics',
      uri: `${rf}/Systems/${rack}-${node}/PCIeDevices/${gpuId}/Metrics`,
    },
    {
      name: 'GPU accelerator clock',
      group: 'Performance',
      value: `${latestClock.toFixed(0)} MHz`,
      threshold: 'warn < 1,600 MHz',
      status: latestClock < 1600 ? 'Warning' : 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'GPU utilization',
      group: 'Performance',
      value: '91%',
      threshold: 'info > 95%',
      status: 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'GPU memory utilization',
      group: 'Performance',
      value: '84%',
      threshold: 'info > 95%',
      status: 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'ECC correctable errors',
      group: 'Performance',
      value: '0',
      threshold: 'warn > 0',
      status: 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'ECC uncorrectable errors',
      group: 'Performance',
      value: '0',
      threshold: 'crit > 0',
      status: 'Normal',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'GPU throttle reason',
      group: 'Performance',
      value: capped ? 'Power cap' : hot ? 'Thermal' : 'None',
      threshold: 'must be None',
      status: scenarioKey === 'healthy' ? 'Normal' : 'Warning',
      source: 'OEM MetricReport',
      uri: `${rf}/TelemetryService/MetricReports/${rack}-${node}-${gpuId}`,
    },
    {
      name: 'System model',
      group: 'Inventory',
      value: 'AI Compute Node',
      threshold: 'inventory',
      status: 'Info',
      source: 'ComputerSystem',
      uri: `${rf}/Systems/${rack}-${node}`,
    },
    {
      name: 'BMC firmware',
      group: 'Inventory',
      value: '7.10.30',
      threshold: 'approved baseline',
      status: 'Normal',
      source: 'UpdateService',
      uri: `${rf}/UpdateService/FirmwareInventory/BMC-${rack}-${node}`,
    },
    {
      name: 'BIOS version',
      group: 'Inventory',
      value: '2.4.1',
      threshold: 'approved baseline',
      status: 'Normal',
      source: 'SoftwareInventory',
      uri: `${rf}/UpdateService/FirmwareInventory/BIOS-${rack}-${node}`,
    },
    {
      name: 'GPU firmware',
      group: 'Inventory',
      value: '96.00.A1',
      threshold: 'approved baseline',
      status: 'Normal',
      source: 'SoftwareInventory',
      uri: `${rf}/UpdateService/FirmwareInventory/${gpuId}`,
    },
    {
      name: 'Redfish schema',
      group: 'Inventory',
      value: '1.20.1',
      threshold: 'supported',
      status: 'Info',
      source: 'ServiceRoot',
      uri: `${rf}`,
    },
  ];
}
