apiVersion: 1

datasources:
  - name: RackLens ClickHouse
    uid: racklens-clickhouse
    type: grafana-clickhouse-datasource
    access: proxy
    jsonData:
      host: clickhouse
      port: 9000
      protocol: native
      username: default
      defaultDatabase: racklens
      tlsSkipVerify: true
    secureJsonData:
      password: $CLICKHOUSE_PASSWORD
    isDefault: true
    editable: true
